name: Run GoLang
on: pull_request

env:
  GO_VERSION: 1.18

jobs:
  pullrequest:
    name: golang
    runs-on: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Run Go Lang Pull Request
        run: |
          cd code/go && \
          ls && \
          go mod init pullrequest && \
          ls && \
          go run pull-request.go